apiVersion: v1
kind: ServiceAccount
metadata:
  name: acvii
# + ClusterRole
# + ClusterRoleBinding
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: acvii-test
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 11Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /acvii/test
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: acvii-cmd
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 11Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /acvii/cmd
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: acvii-pkg
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 11Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /acvii/pkg
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: acvii-internal
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 11Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /acvii/internal
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acvii-test
  namespace: default
spec:
  resources:
    requests:
      storage: 11Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: acvii-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acvii-pkg
  namespace: default
spec:
  resources:
    requests:
      storage: 11Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: acvii-pkg
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acvii-internal
  namespace: default
spec:
  resources:
    requests:
      storage: 11Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: acvii-internal
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acvii-cmd
  namespace: default
spec:
  resources:
    requests:
      storage: 11Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: acvii-cmd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: acvii
    app.kubernetes.io/component: acvii
    app.kubernetes.io/version: "1.0"
    statefulset.kubernetes.io/pod-name: acvii
  name: acvii
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: acvii
  template:
    metadata:
      labels:
        app.kubernetes.io/name: acvii
        app.kubernetes.io/component: acvii
        app.kubernetes.io/version: "1.0"
        statefulset.kubernetes.io/pod-name: acvii
    spec:
      serviceAccount: acvii
      automountServiceAccountToken: true
      containers:
        - name: acvii
          image: achoistic98/acvii:v0.0.1
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /acvii/test
              name: acvii-test
            - mountPath: /acvii/pkg
              name: acvii-pkg
            - mountPath: /acvii/internal
              name: acvii-internal
            - mountPath: /acvii/cmd
              name: acvii-cmd
      volumes:
        - name: acvii-test
          persistentVolumeClaim:
            claimName: acvii-test
        - name: acvii-pkg
          persistentVolumeClaim:
            claimName: acvii-pkg
        - name: acvii-internal
          persistentVolumeClaim:
            claimName: acvii-internal
        - name: acvii-cmd
          persistentVolumeClaim:
            claimName: acvii-cmd

---
apiVersion: v1
kind: Service
metadata:
  name: acvii
spec:
  selector:
    app.kubernetes.io/name: acvii
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32100
---