version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./ci:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock